# Generated by Django 6.0.4 on 2026-05-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificationevent_is_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Space',
        ),
    ]
