# Generated by Django 5.1.7 on 2026-04-16 08:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('Project', 'Project'), ('Sprint', 'Sprint'), ('Member', 'Member')], max_length=20)),
                ('scope_id', models.IntegerField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('velocity', models.FloatField(default=0.0)),
                ('open_issues', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'progress_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Software', 'Software'), ('Business', 'Business'), ('Support', 'Support')], default='Software', max_length=20)),
                ('visibility', models.CharField(choices=[('Private', 'Private'), ('Internal', 'Internal'), ('Public', 'Public')], default='Private', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived'), ('Closed', 'Closed')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='MFAConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('secret', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=False)),
                ('method', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mfa_configs',
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('payload_json', models.JSONField(default=dict)),
                ('channel', models.CharField(choices=[('WebSocket', 'WebSocket')], default='WebSocket', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jira_back_end.project')),
            ],
            options={
                'db_table': 'notification_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CumulativeFlowDiagram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_json', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfd_charts', to='jira_back_end.project')),
            ],
            options={
                'db_table': 'cumulative_flow_diagrams',
            },
        ),
        migrations.CreateModel(
            name='ProjectBoard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('board_type', models.CharField(choices=[('Kanban', 'Kanban'), ('Scrum', 'Scrum')], default='Kanban', max_length=20)),
                ('view_mode', models.CharField(choices=[('List', 'List'), ('Board', 'Board'), ('Timeline', 'Timeline')], default='Board', max_length=20)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='jira_back_end.project')),
            ],
            options={
                'db_table': 'project_boards',
            },
        ),
        migrations.CreateModel(
            name='BoardFilter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.CharField(blank=True, choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20, null=True)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='jira_back_end.projectboard')),
            ],
            options={
                'db_table': 'board_filters',
            },
        ),
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('wip_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('is_done_column', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='jira_back_end.projectboard')),
            ],
            options={
                'db_table': 'board_columns',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='jira_back_end.project')),
            ],
            options={
                'db_table': 'project_dashboards',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Burndown', 'Burndown'), ('Velocity', 'Velocity'), ('CFD', 'Cumulative Flow Diagram'), ('OpenIssues', 'Open Issues'), ('RecentActivity', 'Recent Activity')], max_length=30)),
                ('position', models.PositiveIntegerField(default=0)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='jira_back_end.projectdashboard')),
            ],
            options={
                'db_table': 'dashboard_widgets',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('InProgress', 'In Progress'), ('Released', 'Released'), ('Archived', 'Archived')], default='Planned', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='jira_back_end.project')),
            ],
            options={
                'db_table': 'releases',
            },
        ),
        migrations.CreateModel(
            name='ReleaseDashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('resolved_issues', models.PositiveIntegerField(default=0)),
                ('remaining_issues', models.PositiveIntegerField(default=0)),
                ('release', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='jira_back_end.release')),
            ],
            options={
                'db_table': 'release_dashboards',
            },
        ),
        migrations.CreateModel(
            name='ReleaseHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_history', to='jira_back_end.project')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='jira_back_end.release')),
            ],
            options={
                'db_table': 'release_history',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_markdown', models.TextField()),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('release', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='jira_back_end.release')),
            ],
            options={
                'db_table': 'release_notes',
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV')], max_length=10)),
                ('file_url', models.URLField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='jira_back_end.progressreport')),
            ],
            options={
                'db_table': 'report_exports',
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('goal', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Active', 'Active'), ('Closed', 'Closed')], default='Planned', max_length=20)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='jira_back_end.projectboard')),
            ],
            options={
                'db_table': 'sprints',
            },
        ),
        migrations.CreateModel(
            name='RetrospectiveBoard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('format', models.CharField(default='Start/Stop/Continue', max_length=100)),
                ('is_open', models.BooleanField(default=False)),
                ('sprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retrospective', to='jira_back_end.sprint')),
            ],
            options={
                'db_table': 'retrospective_boards',
            },
        ),
        migrations.CreateModel(
            name='BurndownChart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_json', models.JSONField(default=dict)),
                ('sprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='burndown_chart', to='jira_back_end.sprint')),
            ],
            options={
                'db_table': 'burndown_charts',
            },
        ),
        migrations.CreateModel(
            name='SprintReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_tickets', models.PositiveIntegerField(default=0)),
                ('done_tickets', models.PositiveIntegerField(default=0)),
                ('remaining_tickets', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='jira_back_end.sprint')),
            ],
            options={
                'db_table': 'sprint_reports',
            },
        ),
        migrations.CreateModel(
            name='Swimlane',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Epic', 'Epic'), ('Assignee', 'Assignee')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimlanes', to='jira_back_end.projectboard')),
            ],
            options={
                'db_table': 'swimlanes',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description_markdown', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature'), ('Task', 'Task'), ('Epic', 'Epic'), ('Story', 'Story'), ('SubTask', 'Sub-Task')], default='Task', max_length=20)),
                ('priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('ToDo', 'To Do'), ('InProgress', 'In Progress'), ('InReview', 'In Review'), ('Done', 'Done')], default='ToDo', max_length=20)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('estimate_story_points', models.FloatField(blank=True, null=True)),
                ('estimate_hours', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='jira_back_end.boardcolumn')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='jira_back_end.project')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='jira_back_end.release')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='jira_back_end.sprint')),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jira_back_end.ticket')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jira_back_end.ticket')),
            ],
            options={
                'db_table': 'attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='jira_back_end.ticket')),
            ],
            options={
                'db_table': 'ticket_audit_logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketImportJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('CSV', 'CSV'), ('Markdown', 'Markdown')], max_length=20)),
                ('source_file_url', models.URLField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='jira_back_end.project')),
            ],
            options={
                'db_table': 'ticket_import_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link_type', models.CharField(choices=[('Blocks', 'Blocks'), ('BlockedBy', 'Blocked By'), ('Duplicates', 'Duplicates'), ('RelatedTo', 'Related To')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='jira_back_end.ticket')),
                ('target_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='jira_back_end.ticket')),
            ],
            options={
                'db_table': 'ticket_links',
            },
        ),
        migrations.CreateModel(
            name='TicketMovement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('moved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='jira_back_end.boardcolumn')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_movements', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='jira_back_end.ticket')),
                ('to_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='jira_back_end.boardcolumn')),
            ],
            options={
                'db_table': 'ticket_movements',
                'ordering': ['-moved_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hours_spent', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='jira_back_end.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'time_entries',
            },
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('preferences_json', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='VelocityChart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_json', models.JSONField(default=dict)),
                ('sprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='velocity_chart', to='jira_back_end.sprint')),
            ],
            options={
                'db_table': 'velocity_charts',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('visibility', models.CharField(choices=[('Private', 'Private'), ('Internal', 'Internal'), ('Public', 'Public')], default='Private', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='jira_back_end.organization')),
            ],
            options={
                'db_table': 'workspaces',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='jira_back_end.workspace'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('invite_link', models.URLField()),
                ('expires_at', models.DateTimeField()),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='jira_back_end.workspace')),
            ],
            options={
                'db_table': 'invitations',
            },
        ),
        migrations.CreateModel(
            name='OAuthAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('GitHub', 'GitHub'), ('Google', 'Google')], max_length=20)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oauth_accounts',
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
        migrations.CreateModel(
            name='ProjectFavorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='jira_back_end.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_favorites',
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('ChefDeProjet', 'Chef de Projet'), ('Developpeur', 'Développeur'), ('Observateur', 'Observateur')], default='Developpeur', max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='jira_back_end.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_members',
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Like', 'Like'), ('Love', 'Love'), ('Laugh', 'Laugh'), ('Eyes', 'Eyes'), ('Rocket', 'Rocket')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='jira_back_end.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reactions',
                'unique_together': {('comment', 'user', 'type')},
            },
        ),
        migrations.CreateModel(
            name='RecentProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_access_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_pinned', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_accesses', to='jira_back_end.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recent_projects',
                'ordering': ['-last_access_at'],
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='TicketAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='jira_back_end.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket_assignments',
                'unique_together': {('ticket', 'user')},
            },
        ),
    ]
