# Generated by Django 6.0.4 on 2026-04-22 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='visibility',
        ),
    ]
