# Generated by Django 6.0.4 on 2026-04-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_remove_workspace_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
