# Generated by Django 6.0.4 on 2026-05-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_organization_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20),
        ),
    ]
