# Generated by Django 6.0.4 on 2026-04-19 01:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priorities', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'core_dashboard',
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=50)),
                ('scope_id', models.UUIDField()),
                ('completion_rate', models.FloatField(default=0.0)),
                ('velocity', models.FloatField(default=0.0)),
                ('open_issues', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_progress_report',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100)),
                ('target_date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('released', 'Released')], default='planned', max_length=20)),
            ],
            options={
                'db_table': 'core_release',
                'ordering': ['-target_date'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('resolved_issues', models.IntegerField(default=0)),
                ('remaining_issues', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'core_release_dashboard',
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('goal', models.TextField(blank=True, default='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('closed', 'Closed')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_sprint',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SprintReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_tickets', models.IntegerField(default=0)),
                ('done_tickets', models.IntegerField(default=0)),
                ('remaining_tickets', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_sprint_report',
            },
        ),
        migrations.AddField(
            model_name='boardcolumn',
            name='is_done_column',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardcolumn',
            name='wip_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='pricing_plan_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BacklogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(default=0)),
                ('priority_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlog', to='project.project')),
            ],
            options={
                'db_table': 'core_backlog_item',
                'ordering': ['rank'],
            },
        ),
    ]
