# Generated by Django 6.0.4 on 2026-04-19 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_alter_mfaconfig_user_and_more'),
        ('project', '0002_boardfilter_dashboard_progressreport_release_and_more'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backlogitem',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backlog_item', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='boardfilter',
            name='assignees',
            field=models.ManyToManyField(blank=True, to='accounts.user'),
        ),
        migrations.AddField(
            model_name='boardfilter',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectboard'),
        ),
        migrations.AddField(
            model_name='boardfilter',
            name='labels',
            field=models.ManyToManyField(blank=True, to='tickets.ticketlabel'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='release',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='project.project'),
        ),
        migrations.AddField(
            model_name='releasedashboard',
            name='release',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='project.release'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='project.projectboard'),
        ),
        migrations.AddField(
            model_name='sprintreport',
            name='sprint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_report', to='project.sprint'),
        ),
    ]
