# Generated by Django 6.0.4 on 2026-05-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
