# Generated by Django 6.0.4 on 2026-04-19 01:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('project', '0003_backlogitem_ticket_boardfilter_assignees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='boardcolumn',
            options={},
        ),
        migrations.AlterModelOptions(
            name='progressreport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sprint',
            options={},
        ),
        migrations.RemoveField(
            model_name='boardfilter',
            name='assignees',
        ),
        migrations.RemoveField(
            model_name='boardfilter',
            name='priorities',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pricing_plan_id',
        ),
        migrations.RemoveField(
            model_name='projectboard',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='created_at',
        ),
        migrations.AddField(
            model_name='boardfilter',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardfilter',
            name='priority',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('closed', 'Closed')], default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('software', 'Software'), ('business', 'Business'), ('support', 'Support')], default='software', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('internal', 'Internal'), ('public', 'Public')], default='private', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='orgs.workspace'),
        ),
        migrations.AddField(
            model_name='projectboard',
            name='board_type',
            field=models.CharField(choices=[('kanban', 'Kanban'), ('scrum', 'Scrum')], default='kanban', max_length=50),
        ),
        migrations.AddField(
            model_name='projectboard',
            name='view_mode',
            field=models.CharField(choices=[('list', 'List'), ('board', 'Board'), ('timeline', 'Timeline')], default='board', max_length=50),
        ),
        migrations.AlterField(
            model_name='boardcolumn',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='boardcolumn',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boardfilter',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='project.projectboard'),
        ),
        migrations.RemoveField(
            model_name='boardfilter',
            name='labels',
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='scope',
            field=models.CharField(choices=[('project', 'Project'), ('sprint', 'Sprint'), ('member', 'Member')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='release',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'InProgress'), ('released', 'Released'), ('archived', 'Archived')], default='planned', max_length=50),
        ),
        migrations.AlterField(
            model_name='release',
            name='tag',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='goal',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('closed', 'Closed')], default='planned', max_length=50),
        ),
        migrations.AlterField(
            model_name='sprintreport',
            name='sprint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='project.sprint'),
        ),
        migrations.AlterModelTable(
            name='boardcolumn',
            table=None,
        ),
        migrations.AlterModelTable(
            name='progressreport',
            table=None,
        ),
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
        migrations.AlterModelTable(
            name='projectboard',
            table=None,
        ),
        migrations.AlterModelTable(
            name='release',
            table=None,
        ),
        migrations.AlterModelTable(
            name='releasedashboard',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sprint',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sprintreport',
            table=None,
        ),
        migrations.CreateModel(
            name='BurndownChart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_json', models.JSONField(default=dict)),
                ('sprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='burndown_chart', to='project.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='CumulativeFlowDiagram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_json', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfds', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('burndown', 'Burndown'), ('velocity', 'Velocity'), ('cfd', 'CFD'), ('open_issues', 'OpenIssues'), ('recent_activity', 'RecentActivity')], max_length=50)),
                ('position', models.IntegerField(default=0)),
                ('config_json', models.JSONField(default=dict)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='project.projectdashboard')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('chef_de_projet', 'ChefDeProjet'), ('developpeur', 'Developpeur'), ('observateur', 'Observateur')], default='observateur', max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecentProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_access_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_accessed_by', to='project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archived_at', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_histories', to='project.project')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.release')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_markdown', models.TextField(blank=True)),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('release', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='release_note', to='project.release')),
            ],
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], max_length=50)),
                ('file_url', models.URLField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='project.progressreport')),
            ],
        ),
        migrations.CreateModel(
            name='RetrospectiveBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(max_length=255)),
                ('sprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retrospective_board', to='project.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Swimlane',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('epic', 'Epic'), ('assignee', 'Assignee')], max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimlanes', to='project.projectboard')),
            ],
        ),
        migrations.CreateModel(
            name='VelocityChart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_json', models.JSONField(default=dict)),
                ('sprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='velocity_chart', to='project.sprint')),
            ],
        ),
        migrations.DeleteModel(
            name='BacklogItem',
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.AddField(
            model_name='boardfilter',
            name='labels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
