# Generated by Django 6.0.4 on 2026-05-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
