# Generated by Django 6.0.4 on 2026-04-19 01:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_alter_mfaconfig_user_and_more'),
        ('project', '0002_boardfilter_dashboard_progressreport_release_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description_markdown', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature'), ('task', 'Task')], max_length=50)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='open', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='', max_length=50)),
                ('estimate_story_points', models.FloatField(default=0.0)),
                ('estimate_hours', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='project.boardcolumn')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='project.project')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='project.release')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='project.sprint')),
            ],
            options={
                'db_table': 'core_ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to='accounts.user')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_assignments', to='accounts.user')),
            ],
            options={
                'unique_together': {('ticket', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TicketLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='tickets.ticket')),
            ],
            options={
                'unique_together': {('ticket', 'label')},
            },
        ),
        migrations.CreateModel(
            name='TicketLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(choices=[('blocks', 'Blocks'), ('blocked_by', 'Blocked By'), ('duplicates', 'Duplicates'), ('related', 'Related To')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='tickets.ticket')),
                ('target_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='tickets.ticket')),
            ],
            options={
                'unique_together': {('source_ticket', 'target_ticket', 'link_type')},
            },
        ),
        migrations.CreateModel(
            name='TicketMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('move_type', models.CharField(blank=True, max_length=50, null=True)),
                ('from_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_from', to='project.boardcolumn')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='tickets.ticket')),
                ('to_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_to', to='project.boardcolumn')),
            ],
            options={
                'db_table': 'core_ticket_movement',
                'ordering': ['-moved_at'],
                'indexes': [models.Index(fields=['ticket', 'moved_at'], name='core_ticket_ticket__bcf094_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hours_spent', models.FloatField()),
                ('comment', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='accounts.user')),
            ],
            options={
                'db_table': 'core_time_entry',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['ticket', 'started_at'], name='core_time_e_ticket__0e7e3a_idx'), models.Index(fields=['user', 'started_at'], name='core_time_e_user_id_db0df2_idx')],
            },
        ),
    ]
