# Generated by Django 6.0.4 on 2026-05-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature'), ('task', 'Task'), ('epic', 'Epic'), ('story', 'Story'), ('sub_task', 'SubTask'), ('vulnerability', 'Security Vulnerability'), ('patch', 'Patch'), ('incident', 'Incident'), ('deployment', 'Deployment'), ('monitoring', 'Monitoring'), ('rollback', 'Rollback')], default='task', max_length=50),
        ),
    ]
