# Generated by Django 6.0.4 on 2026-04-19 01:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_dashboard_user_alter_boardcolumn_options_and_more'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('markdown', 'Markdown')], max_length=50)),
                ('source_file_url', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketSearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('priority', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=50)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('from_date', models.DateTimeField(blank=True, null=True)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ticketlabel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ticketlabel',
            name='ticket',
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ticketmovement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='ticketmovement',
            name='core_ticket_ticket__bcf094_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='core_time_e_ticket__0e7e3a_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='core_time_e_user_id_db0df2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='ticketassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ticketlink',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='file',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='mime_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('todo', 'ToDo'), ('in_progress', 'InProgress'), ('in_review', 'InReview'), ('done', 'Done')], default='todo', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature'), ('task', 'Task'), ('epic', 'Epic'), ('story', 'Story'), ('sub_task', 'SubTask')], default='task', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketlink',
            name='link_type',
            field=models.CharField(choices=[('blocks', 'Blocks'), ('blocked_by', 'BlockedBy'), ('duplicates', 'Duplicates'), ('related_to', 'RelatedTo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketmovement',
            name='moved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='ticket',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ticketmovement',
            table=None,
        ),
        migrations.AlterModelTable(
            name='timeentry',
            table=None,
        ),
        migrations.AddField(
            model_name='ticketauditlog',
            name='actor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketauditlog',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketimportjob',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='ticketsearchquery',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TicketLabel',
        ),
        migrations.RemoveField(
            model_name='ticketmovement',
            name='move_type',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='created_at',
        ),
    ]
